baseURL = "/"
title = "Beyond The Software"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Beyond the Software" # title for frontpage, may include image
copyright = "Darrin Braun"
description = 'It is about the people who run your business everyday.<br /> We go beyond the software, empowering your team <br/ > to efficiently and profitably operate the business.
'
startbuttonText = "Request Consultation"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

# language specific options

[languages.en]
weight = 0
languageName = "English"
