baseURL = "/"
title = "Beyond The Software"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Beyond the Software" # title for frontpage, may include image
copyright = "Darrin Braun"
description = 'It is about the people who run your business everyday.<br /> We go beyond the software, empowering your team <br/ > to efficiently and profitably operate the business.'
startbuttonText = "Request Consultation"
startbuttonLink = "#contact"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

#rename to a toml file
#and add to end of code
[params.one]
enable = true
title = 'What you can expect'
body = '''
We will work with your leadership team to develop a plan. Review and understand, develop a strategy, communicate, execute. Revist these as project moves forward.
'''

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "Quality"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Love"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Code"

[params.two]
enable = true

[[params.two.section]]
img = "https://raw.githubusercontent.com/beyondthesoftware/website/master/download.jpeg"
title = 'Develop a Strategy'
body = 'Utilizing existing knowledge and insignt...'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Communicate our intent<br />elementum magna'
body = 'Clearly communicate intent... Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Execute on that clearly communicated plan<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = true
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-headphones"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart-o"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag-o"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Test"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+12622366716"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "darrin@beyondthesoftware.com"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""
# language specific options

[languages.en]
weight = 0
languageName = "English"
