baseURL = "/"
title = "Beyond The Software"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Beyond the Software" # title for frontpage, may include image
copyright = "Darrin Braun"
description = 'It is about the people who run your business everyday.<br /> We go beyond the software, empowering your team <br/ > to efficiently and profitably operate the business.'
startbuttonText = "Request Consultation"
startbuttonLink = "#contact"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"
#un-comment + edit later
#[[params.menu.main]]
#url = '/Posts/index.html'
#title = "Posts"
[[params.menu.main]]
url = 'https://www.linkedin.com/in/darrinbraun/'
title = "[In]"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

#delete this  | and add all the code
#             v
[params.one]
enable = true
title = '⬇'
body = '''
..
'''

[params.contact]
enable = true
title = "Contact"
body = "<form action='https://formspree.io/f/{form_id}' method='post'>
  <label for='email'>Your Email</label>
  <input name='Email' id='email' type='email'>
  <button type='submit'>Submit</button>
</form>"
phone = "+12622366716"
address = "Pewaukee, Wi USA"
email = "darrin@beyondthesoftware.com"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""
# language specific options

[languages.en]
weight = 0
languageName = "English"
